name: veteranns
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.1.2
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  url_launcher: ^6.2.5
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  flutter_stripe: ^10.1.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/icons/
    - assets/images/
